version: "3"
services:
  app:
    #Would be implemented to rebuild on change for developpement 
    #volumes:
    #  - .:/usr/src/MathEnJeu
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes: 
      - ./questions_png:/usr/src/MathEnJeu/dist/server/assets/


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    build: ./database
    container_name: db

