version: "3"
services:
  app:
    env_file:
      - .env
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes: 
      - ./questions_png:/usr/src/MathEnJeu/dist/server/assets/
      - ./question_images:/usr/src/MathEnJeu/dist/server/assets/question_images

  web:
    container_name: vue_app
    ports: 
      - "80:80"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    build: ./database
    container_name: db

