version: "3"
services:
  app:
    build: 
      context: ./game
      dockerfile: Dockerfile.dev
    volumes: 
      - ./game/src:/usr/src/MathEnJeu/src

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes: 
      - ./web/src:/app/src
    stdin_open: true
    tty: true
    environment: 
      - CHOKIDAR_USEPOLLING=true
