version: "2"
services:
  app:
    build: .
    #Doesn't seem to work with docker toolkit (legacy) for windows
    #Would be implemented to rebuild on change for developpement
    #volumes:
    #  - .:/usr/src/MathEnJeu
    ports:
      - "8080:8080"
