version: "2"
services:
  app:
    build: ./game
    #Would be implemented to rebuild on change for developpement
    #volumes:
    #  - .:/usr/src/MathEnJeu
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    build: ./database
    container_name: db
    image: mysql

